@startuml
left to right direction
actor "Employé" as dude
actor "LDAP" as ldap
rectangle "Gestion de profil" {
  usecase "Se Connecter" as login
  usecase "Authentifier utilisateur" as checkAuth
  usecase "Rejeter connexion" as failAuth
  usecase "Sélectionner photo" as pickPhoto
  usecase "Transmettre photo" as uploadPhoto
  usecase "Remplacer photo" as updatePhoto
  usecase "Notifier succès" as notifySuccess
}

dude -- login
dude -- pickPhoto
dude -- notifySuccess

checkAuth -- ldap
failAuth -- ldap
uploadPhoto -- ldap
updatePhoto -- ldap
notifySuccess -- ldap

login ..> checkAuth: include
login <.. failAuth: extend
pickPhoto ..> uploadPhoto
pickPhoto <.. updatePhoto
updatePhoto ..> notifySuccess

@enduml
