@startuml
left to right direction
actor "Employé" as dude


rectangle "Gestionnaire de Profil" {
  usecase "Changer photo profil" as changePhoto
  usecase "Se Connecter" as login
}

dude -- changePhoto
changePhoto .> login: <<include>>


@enduml
