@startuml
left to right direction
actor "Client" as client
rectangle "Application Bancaire" {
  usecase "Effectuer virement" as makeTransfer
  usecase "S'authentifier" as login
}

client -- makeTransfer
makeTransfer .> login: <<include>>

@enduml
