L’Afpa de Rochefort décide de mettre en place une application de co-voiturage pour simplifier la
mise en contact du personnel et des stagiaires se rendant au centre.

Cette application devra permettre aux utilisateurs de se connecter avec leur identifiant Afpa (unique).
Une fois connectés, les utilisateurs pourront consulter les trajets disponibles.

Un « trajet » est défini comme un aller simple allant d’un lieu précis (défini par une adresse) au site de l’Afpa.
Le retour de l’Afpa à l’adresse est aussi considéré comme un trajet.
Un aller-retour sera appelé un « voyage ».

Les utilisateurs pourront s’inscrire à autant de trajets qu’ils le souhaitent,
dans la limite des places disponibles dans une voiture
(on considèrera qu’au maximum 4 places sont disponibles dans un véhicule).
Lors de l’inscription à un trajet, l’utilisateur devra choisir une durée de validité de son inscription.

Les utilisateurs devront aussi pouvoir inscrire de nouveaux trajets (sans limite de nombre) en
précisant:
    • leur lieu de départ ;
    • l’heure du départ ;
    • les jours de la semaine concerné par un trajet régulier (puisqu’il est possible, pour certains,
de ne pas faire le trajet tous les jours) ;
    • le type de véhicule utilisé en précisant la place éventuelle pour les bagages (certains
stagiaires ont du matériel à transporter) ;
    • si le véhicule est fumeur ou non.

Attention, les trajets pourront être réguliers ou ponctuels, dans le cas de trajets réguliers une date
de validité devra être prise en compte.

@startuml
left to right direction
actor "Utilisateur" as user

rectangle "Application Co-voiturage" {
    usecase "Se Connecter" as login
    usecase "Consulter trajets" as browseRoutes
    usecase "S'inscrire aux trajets" as checkInRoutes
    usecase "Proposer des trajets" as postRoutes
}

user -- browseRoutes
browseRoutes ..> login: <<include>>
user -- checkInRoutes
user -- postRoutes
postRoutes ..> login: <<include>>
checkInRoutes .> browseRoutes: <<extend>>
@enduml